name: dog_breed_app
description: 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.0
  loading_indicator: ^3.0.3
  flutter_svg: ^1.0.3
  google_fonts: ^4.0.4
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  http: ^0.13.3


dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env
 

  fonts:
    - family: Galano
      fonts:
       - asset: assets/fonts/Galano-Grotesque-Alt-Medium.otf
    # - family: RobotoMono
    #   fonts:
    #    - asset: assets/fonts/RobotoMono-Regular.ttf
    #    - asset: assets/fonts/AnekGurmukhi-Regular.ttf
    #    - asset: assets/fonts/AnekGurmukhi-Bold.ttf
    # - family: Manrope
    #   fonts:
    #    - asset: assets/fonts/Cabin-Medium.ttf
